language: python
python:
  - '3.5.2'

branches:
  only:
    - staging

before_install:
  - chmod +x manage.py

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
