# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openfood.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=1)),
                ('url', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('product_img_url', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(related_name='products', through='openfood.Position', to='openfood.Category')),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openfood.Product'),
        ),
    ]
