# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorized',
            field=models.IntegerField(default=0),
        ),
    ]
